### ISSUE TITLE
Support comparisons with null

### ISSUE THREAD

**Issue by tmcw** [mapnik/carto-spec#2]
```
#thing[FIELD != null] {}
```

**Comment by tmcw** [comment]
Also check true/false

**Comment by springmeyer** [comment]
see https://github.com/mapnik/mapnik/issues/794

**Comment by springmeyer** [comment]
basically you can do that in mapnik now, but as per db's like postgres we need to decide if we really want `!= null` or if we mean `is not null`.

**Comment by tmcw** [comment]
Closing; CartoCSS is stable.
